### PR TITLE
Add option to remove NOT NULL constratins #4316

### PR DESCRIPTION
**Pull request by phebal**
After creating database schema optionally remove NOT NULL
constraints on all but the primary-key columns.

### CODE REVIEW

**Comment by phebal** [comment]
Sorry, forgot the tests.  Will re-open once I finish them.

**Comment by phebal** [comment]
Added specs.

**Comment by hannahwhy** [comment]
There's a few typos and the like that I would like to see addressed.

**Comment by phebal** [comment]
Frank will take care of the typos you pointed out in his next PR since this got merged already.  Sorry about this.

**Pull request merged**
